### PR TITLE
[Enhancement] Jekyll 4.x compatibility

### PR DESCRIPTION
**Pull request by cristianocasella**
This PR is going to fix https://github.com/daviddarnes/alembic/issues/146 adding compatibility to the Jekyll 4.x engine.

Tested with Jekyll 4.1.1

I had to deactivate `css_inline` feature, it's not working anymore and I'm not been able to fix it, any help is welcomed.

### CODE REVIEW

**Comment by daviddarnes** [comment]
Really appreciate you sorting this out @cristianocasella! I’ve only just recently got back into Jekyll projects I work on and I find the process of updating gems a little daunting. I’ll check out your branch and see if I can get the in-line css option working 👍

**Comment by cristianocasella** [comment]
Really thanks for your effort and this project, really appreciated, great job!

**Comment by daviddarnes** [comment]
@cristianocasella I've got the inline css option working again, not exactly the same but similar enough. Also put back in the `jekyll-default-layout` gem, I realise you removed it due to incompatibility but it's needed for many of the pages and existing users will expect it to just work. Hoping to get this fixed by requesting the gem to be published here:
https://github.com/benbalter/jekyll-default-layout/pull/12

Overall I think this may have to be marked as a major version bump, as in Alembic 4.0, since it's newer compatibility and it will break a few things for people updating.

**Comment by cristianocasella** [comment]
That’s great, let me know if there is anything else I can do to help.

**Comment by daviddarnes** [comment]
@cristianocasella thanks! Would you be able to give me push access to your repo so I can push my changes?

**Comment by cristianocasella** [comment]
it should be done!

Il giorno lun 3 ago 2020 alle ore 13:16 David Darnes <
notifications@github.com> ha scritto:

**Comment by daviddarnes** [comment]
Thanks @cristianocasella! Got it

**Comment by daviddarnes** [comment]
All updated now @cristianocasella, just had to go the long way by making a pull request to your fork and then merge it in. Only things left to do are:
- [ ] Hopefully update the default layout plugin when it's been deployed to rubygems
- [ ] Bump the whole theme to v4 of itself to notify people of breaking changes
- [ ] Merge these changes and create a release

**Comment by cristianocasella** [comment]
Great, thanks for everything, finger crossed for a quick update on the default layout plugin

**Comment by daviddarnes** [comment]
@cristianocasella I've been tipped off that we could remote the default layout plugin entirely if we set defaults in the config for page and post collections. More info here: https://jekyllrb.com/docs/configuration/front-matter-defaults/

Would you mind giving it a go in your fork? If not I'll set up your repo properly on my machine and push to it 😅

**Comment by cristianocasella** [comment]
sure, working on it

**Comment by cristianocasella** [comment]
@daviddarnes fixed the config and tested, now the default layouts are in place.

**Comment by daviddarnes** [comment]
Looks good! Thanks a lot for this work @cristianocasella. Going to merge now, will add some minor tweaks and then submit gem 👍

**Pull request merged**
