### PR TITLE
[Enhancement] Load custom fonts async

### PR DESCRIPTION
**Pull request by studioromeo**
Rather than using a css import for the font use async loading using the print media hack + a few other bits and bobs. For more info check out https://csswizardry.com/2020/05/the-fastest-google-fonts/

Also uses font-display: swap so users are able to read the text even though the font hasn't downloaded yet

Finally uses the latest google font api for including the fonts.

I added a TIP comment to _settings.scss so that people customizing this theme know where to go to register their fonts now but let me know if there needs to be any more docs 🙂

### CODE REVIEW

**Comment by daviddarnes** [comment]
Oh cool! Thanks @studioromeo, would you be able to add how this is done into the readme? Might be better than redirecting people. Also could be a good idea to wrap the front URL in a variable in the `_config.yaml`, what do you think? I had it in the CSS so people could change the font while styling their site, but a config variable might be the next best thing

**Comment by ao5357** [comment]
With [core web vitals](https://web.dev/vitals/) factoring into LightHouse performance scores, I saw my scores improve when removing the print media hack. I'm pretty sure this is due to cumulative layout shift. Unless you're serving critical CSS it's probably best for performance and UX to omit the hack.

One possible compromise approach is to set the hack as an option via a boolean flag in `_config.yml`.

In my alembic-inspired project, finished-starter, we use this technique: https://github.com/lowerbarriers/finished-starter/blob/gh-pages/_config.yml#L29
...and then in the head: https://github.com/lowerbarriers/finished-starter/blob/gh-pages/_includes/head/head.html#L12

Note that there's also a mechanism in those files for preloading woff fonts, though those are locally-served in that project rather than coming from Google Fonts, so YMMV.

Hope this helps.

**Comment by studioromeo** [comment]
I've hopefully done this in 3c6a26f but let me know if theres anything you'd like changed 🙂 

In my testing I found that this has an impact of 200ms on the first content paint and about 2 lighthouse performance points. Unfortunately this doesn't reduce CLS. That could be improved by careful choice of a fallback to reduce the amount the text changes when the font is swapped in, or avoid the issue entirely by not using a custom font.

Before | After
----- | -----
Screenshot 2020-10-28 at 19 10 54|Screenshot 2020-10-28 at 19 10 48

**Comment by daviddarnes** [comment]
I'm just getting my head around this and I love it! First time seeing this method of implementing fonts, so certainly a learning experience.

@studioromeo could the key names be modified? I think `fonts` would be enough, plus `preconnect_urls` and `font_urls` to nest inside might be better naming conventions and provide some explanation to their usage. Also can we change the include to `site-fonts.html`? The nature of the theme is both custom and not really 😅 

@ao5357 flattered that your theme is inspired by mine in any way! I'm ok with this getting merged as it, but I'm willing to do some testing if you still this it's not a good idea? Seems as though @studioromeo has done that for us though 👍

**Comment by ao5357** [comment]
@daviddarnes @studioromeo turns out my main concern (that there might be a `rel` mismatch in the preload) was unfounded. Heck, if it works for Harry Roberts it should work anywhere (except when it comes to formatting HTML attributes, in which case he is clearly and emphatically wrong). David's suggestion to change the variable names would go a long way to disambiguating the preload -- after all, it 's a CSS file containing webfont declarations, rather than font files themselves.

In any event, this technique asyncs and unblocks a request chain that comes from using Google Fonts. With self-hosted fonts you could eliminate the chain and preload the font files directly. In case you wanted to try it, I've added the Merriweather variable font to https://github.com/lowerbarriers/finished-starter/tree/gh-pages/assets/fonts/merriweather

**Comment by studioromeo** [comment]
@daviddarnes I've updated the names based on your suggestions in ec47aae. It's a separate commit just to make the review of changes easier but when you're happy I'll squish it into the original.

**Comment by daviddarnes** [comment]
This is so cool, thank you for adding it @studioromeo! I think I'm going to have to use this feature addition as a reason to make a 0.1 version bump of the theme. I'll get this merged as soon as I can and assemble a release for it!

**Comment by daviddarnes** [comment]
Update: I've made a draft release, but I want to get #155 and #143 in there too but I think they need more tweaks

**Comment by daviddarnes** [comment]
@studioromeo @ao5357 I'm YOLO merging this in as it's been hanging around for way too long. Thanks for all your help, and especially @studioromeo for your contribution!

**Comment by studioromeo** [comment]
@daviddarnes anytime! Thanks for merging 🙂

**Comment by archiewood** [comment]
Maybe this is intended, but if you use the latest ruby gem release, this feature isn't included, I dont think.

I'm sure it was just me being slow, but I spent quite a lot of time hacking aournd with the _config.yml file based in the Netlify deploy, before realising that this isnt in the gem by default.

**Comment by daviddarnes** [comment]
Oh damn you’re right @archiewood. I have 4.2.0 release in draft but never got round to publishing it. Bit too busy I’m afraid 😅
Hopefully I can get to this soon. If you really want the preconnect addition you can always add it manually as the whole meta tag to the head

**Pull request merged**
